### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by pzmarzly**
Closes #31

### CODE REVIEW

**Comment by medape** [comment]
Awesome. Just awesome.

I fixed the installer again, please pull. Your new `img` folder wasn't included.

**Comment by pzmarzly** [comment]
Thanks. Merged the installer fix.

Mapping to [0, 255] happens only on Linux, right? AFAIK on Windows it's mapped to [0, 32768]. Though I think 1 byte of accuracy could be enough for almost all cases. The change isn't necessary right now, but could be useful in the future - it would simplify implementing binary protocol. It could also allow us to use [HashIds](https://hashids.org/), but that [wouldn't be too effective](https://codepen.io/Shawo/pen/QeLrrO).

**Comment by medape** [comment]
Okay. We'll map to [-1, 1] for the momemt and worry about this in the future, then?

By the whay, why use Hashids? Can't we just send arbitrary ASCII bytes, or isn't there a way to do that with JavaScript?

**Comment by pzmarzly** [comment]
> We'll map to [-1, 1] for the momemt and worry about this in the future, then?

If we are to change that, I'd prefer `int:[0, 255]` to `float:[-1, 1]`.

> By the whay, why use Hashids?

HashIds was my first thought when you mentioned sending [0, 255] from JS side. They are usually an easy way to compress integers, but not here apparently.

> Can't we just send arbitrary ASCII bytes, or isn't there a way to do that with JavaScript?

I haven't tried that, but we I can imagine it could cause problems on `JS---console.log()--->Java` boundary (especially ASCII characters such as null bytes and newlines, or non-UTF8 ones). Meanwhile there shouldn't be any problem if we keep sending comma-delimited string from JS and parse it in Java. But it would be nice to test your idea (ASCII bytes) once we try moving to binary protocol.

**Comment by medape** [comment]
> If we are to change that, I'd prefer `int:[0, 255]` to `float:[-1, 1]`.

Okay. [0, 255] is even easier to program right now, and results in shorter messages. I like it. We'll just renormalize for Windows users if they need it.

(I don't really mind either approach, I just want to make sure before making more changes.)

> I haven't tried that, but we I can imagine it could cause problems on `JS---console.log()--->Java` boundary (especially ASCII characters such as null bytes and newlines, or non-UTF8 ones). Meanwhile there shouldn't be any problem if we keep sending comma-delimited string from JS and parse it in Java. But it would be nice to test your idea (ASCII bytes) once we try moving to binary protocol.

`console.log()` will need something human-readable anyways. A string of bytes is useless for debugging.

**Pull request merged**
