### PR TITLE
Installer fix

### PR DESCRIPTION
**Pull request by medape**
I found about this project some days ago via F-Droid.

I'm loving this new version with a WebView, but I spent a long time trying to set it up: pip3 never installed the HTML assets, so I had to download them and move them to the correct path by hand. 

These commits should fix that. I went ahead and added some metadata to the installer script ― I hope you don't mind.

Also, your installation guide still points to the old stable version (the one with two joysticks and no buttons). You might want to change that.

### CODE REVIEW

**Comment by medape** [comment]
I realise now I've only tried it in Linux. The link for the vJoy driver for Windows is broken.

**Comment by rmst** [comment]
Thanks for your help! I like the WebView version, too. It's much more powerful. @pzmarzly made that happen!

**Comment by rmst** [comment]
(Fixed the vjoy link)

**Comment by medape** [comment]
When did you―??

Oh, wow, you were fast. I'll try to fix my other commit.

**Pull request merged**
